# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-28 11:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Technical',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('technical_name', models.CharField(max_length=250)),
                ('technical_description', models.CharField(max_length=500)),
                ('technical_link1', models.CharField(max_length=500)),
                ('technical_logo', models.FileField(upload_to=b'')),
            ],
        ),
    ]
